trigger:

  branches:
    include:
      - "*"
variables:
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    publish: true
  ${{ else }}:
    publish: false
pool:
  vmImage: ubuntu-latest

stages:
- stage: WebBuild
  displayName: Web-Build
  jobs: 
  - job: BuildWeb
    displayName: Build-Web
    pool:
      vmImage: ubuntu-latest
    steps:
      - script: |
          sh <(curl -L https://nixos.org/nix/install) --daemon
        displayName: 'Install Nix'
      - checkout: self
        fetchDepth: 1
      - script: |
          nix develop --command "menu"
        displayName: 'Run commands in devshell'
