# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - "*"
  paths:
    include:
      - content

variables:
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    publish: true
  ${{ else }}:
    publish: false

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Web
    displayName: Web-Build
    jobs:
      - job: BuildWeb
        displayName: Build-Web
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Docker@2
            displayName: Login to docker repo
            inputs:
              containerRegistry: 8237b94b-dadc-4c7b-9927-370a5623f7e7
              command: login
              addPipelineData: false
              addBaseImageData: false
          - bash: |
              docker run --name Pandoc -i \
              -v $(Build.SourcesDirectory):/work \
              -e PUBLISH=${{variables.publish}} \
              sc2containers.azurecr.io/monahven.hugopdf:pandoc
            displayName: Run the pandoc container
          - publish: $(Build.SourcesDirectory)/public
            artifact: WebApp
          - task: AzureStaticWebApp@0
            condition: and(succeeded(), eq(variables.publish, 'true'))
            inputs:
              app_location: /public
              output_location: public
              skip_app_build: true
              azure_static_web_apps_api_token: $(deployment_token)