# https://numtide.github.io/devshell
[[commands]]
name = "build-pdfs"
command = "./pandoc.sh"
help = "Build the PDFs for the project"
category = "build"

[[commands]]
name = "build-pdfs-draft"
command = "./pandoc.sh -d"
help = "Build the PDFs for the project in draft mode"
category = "build"

[[commands]]
name = "build-pdfs-redact"
command = "./pandoc.sh -r"
help = "Build the PDFs for the project in redact mode"
category = "build"

[[commands]]
name = "build-pdfs-redact-draft"
command = "./pandoc.sh -rd"
help = "Build the PDFs for the project in both redact and draft mode"
category = "build"

[[commands]]
name = "build-site"
command = "pnpm build"
help = "Build the site"
category = "build"

[[commands]]
name = "podman-init"
command = "podman machine init && podman-start"
help = "Initialize a podman VM on localhost"
category = "dev"

[[commands]]
name = "podman-build"
command = "podman build -t seccenter ."
help = "Build the container image"
category = "dev"

[[commands]]
name = "podman-run"
command = "podman run -v $(pwd):/data seccenter"
help = "Run the container image"
category = "dev"

[[commands]]
name = "install-node-pkgs"
command = "pnpm i"
help = "Installs all packages in the lock file"
category = "dev"

[[commands]]
name = "clean"
command = '''
  echo "Cleaning the project of all build artifacts and node_modules..."
  rm -rf .direnv node_modules public resources internal .pnpm-store *.err *.log *.core 2>/dev/null
'''
help = "Cleans the project of all build artifacts"
category = "dev"

[[commands]]
name = "run-server"
command = "pnpm dev"
help = "Runs the development server"
category = "author"

[[commands]]
name = "create-news"
command = "pnpm run create content/news/$1.md"
help = "Create a new news post with filename as the first argument. Try not to use spaces in the filename."
category = "author"

[[commands]]
name = "create-policy"
command = "pnpm run create content/docs/isms/$1.md"
help = "Create a new policy with filename as the first argument. Try not to use spaces in the filename."
category = "author"

[[commands]]
name = "audit-compliance"
command = "./scripts/compliance_check_soc2.sh"
help = "Run the SOC2 Type 1 compliance check against the project"
category = "test"

[[commands]]
name = "audit-review-dates"
command = "./scripts/review_date_check.sh"
help = "Check if the documents have been reviewed in the last 12 months from today."
category = "test"

[[commands]]
name = "audit-review-future"
command = "./scripts/review_date_check.sh $1"
help = "Check if the documents have been reviewed in the last 12 months from provided date."
category = "test"

[[commands]]
name = "podman-start"
command = "podman machine start"
help = "Start the podman VM so pandoc can be run"
category = "dev"

[[commands]]
name = "update-node-pkgs"
command = "pnpm update --latest"
help = "Updates all packages in the lock file"
category = "updates"

[[commands]]
name = "update-doks"
command = "pnpm upgrade @hyas/doks-core --latest"
help = "Updates doks to the latest version"
category = "updates"

[[commands]]
name = "update-flake"
command = "nix flake update"
help = "Updates the flake and devshell"
category = "updates"

[devshell]
name = "doks"
motd = '''
  🔨 Welcome to the {44}SC2 Security Center{reset} dev shell
  $(type -p menu &>/dev/null && menu)
'''
packages = [
  "nodePackages.pnpm",
  "pandoc",
  "yq-go",
  "podman",
  "gawk",
  "gnused",
]

# Expose all the dependencies from a package to the environment.
packagesFrom = [
  "direnv",
]