#!/usr/bin/env python3
"""Generate data/scf.{json,yml} from an sc2in/scf checkout.

Usage: gen-scf-catalog.py <scf-dir> [<output-dir>]

Resolves the dataset version from <scf-dir>/.scf-version and reads
data/scf-<version>.json. Emits the flat catalog PolicyPress consumes:
- data/scf.json — bare array of {domain, control_id, control} objects
  (src/control_report.zig reads only JSON arrays)
- data/scf.yml  — same rows for the web templates (load_data in
  templates/SCF/*.html), with a do-not-hand-edit header

Stdlib only. Deterministic output (workbook order, no timestamps) so the
committed artifacts diff cleanly and checks.scf-catalog-fresh can drift-
check them against the pinned scf input.
"""

import json
import sys
from pathlib import Path


def main() -> int:
    if len(sys.argv) < 2:
        print(__doc__, file=sys.stderr)
        return 2
    scf_dir = Path(sys.argv[1])
    out_dir = Path(sys.argv[2]) if len(sys.argv) > 2 else Path(__file__).resolve().parent.parent / "data"

    version = (scf_dir / ".scf-version").read_text().strip()
    dashed = version.replace(".", "-")
    catalog = json.loads((scf_dir / "data" / f"scf-{dashed}.json").read_text())
    families = catalog["families"]

    rows = [
        {
            "domain": families.get(c["family"], c["family"]),
            "control_id": c["control_id"],
            "control": c["title"],
        }
        for c in catalog["controls"]
    ]

    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "scf.json").write_text(
        json.dumps(rows, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )

    # YAML: double-quoted scalars are a superset of JSON strings, so
    # json.dumps gives correct quoting/escaping without a YAML library.
    lines = [
        f"# Generated by tools/gen-scf-catalog.py from sc2in/scf (SCF {version}).",
        "# Do not hand-edit — regenerate with: nix run .#gen-scf-catalog",
    ]
    for row in rows:
        lines.append(f"- domain: {json.dumps(row['domain'], ensure_ascii=False)}")
        lines.append(f"  control_id: {json.dumps(row['control_id'], ensure_ascii=False)}")
        lines.append(f"  control: {json.dumps(row['control'], ensure_ascii=False)}")
    (out_dir / "scf.yml").write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(
        f"wrote {out_dir}/scf.json and scf.yml — SCF {version}: {len(rows)} controls",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
