name: Test

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

env:
  NIXED_USER: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v12
      
      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v7
      
      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.12.0
        
      - name: Run tests
        run: devbox run test
